GPII-3617: Fix exekube rubygem build error - remove gem update
Recent update of rubygems to 3.0.1 causes build to fail:
```
Regenerating binstubs
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --no-ri
```

At the same time the explicit `gem update --system` is not needed
anymore, as recent `grpc` gem release `1.17.1` fixes the issue why this
was originally introduced.